version: 1.0.{build}
image: WMF 5
install:
- ps: >-
    Get-PackageProvider -Name NuGet -Force

    Install-Module -Name Pester -Force

    Install-Module -Name PesterMatchArray -Force
build_script:
- ps: Invoke-Pester -EnableExit